title: Kennisbank Gegevensboekhouding

collections:
  kaarten:
    output: true
    permalink: /:collection/:path/
  besluiten:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      type: kaarten
    values:
      layout: card
      collection: kaarten
  - scope:
      type: besluiten
    values:
      layout: card
      collection: besluiten