name: Build and Deploy Jekyll Site with Symlink

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true  # Zorg ervoor dat de kennisbank submodule wordt opgehaald

    - name: Create symlink for _kaarten
      run: ln -s $GITHUB_WORKSPACE/kennisbank/kaarten $GITHUB_WORKSPACE/_kaarten

    - name: Create symlink for _besluiten
      run: ln -s $GITHUB_WORKSPACE/kennisbank/besluiten $GITHUB_WORKSPACE/_besluiten

    - name: Install Jekyll and dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
