name: pages-rebuild

on:
  schedule:
    - cron: '0 6 * * *' # Automatically rebuild every day at 6:00 UTC

  workflow_dispatch: # Manually rebuild

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
